/**
 * Deterministic field rules — RULE_BASED processing.
 *
 * Every function here is a pure transformation of form answers into the text
 * printed on the sheet. No AI is involved, so the same input always gives the
 * same output (§8.6). Rules are selected by `SheetField.ruleKey`, which an
 * operator picks from a dropdown on the admin screen.
 */

import type { Glossary } from '@/lib/glossary/glossary';
import { buildDescription, buildQualificationLine, type JlptScores } from './jlpt';
import { isNoneOption, japaneseSideOfOption } from '@/lib/style/choice';

export type RuleContext = {
  /** Raw answers keyed by question code, already resolved for the record. */
  answers: Record<string, unknown>;
  glossary: Glossary;
  /** Reference date for age calculation; defaults to today. */
  now?: Date;
  jlpt?: JlptScores | null;
  person?: {
    fullNameEnglish?: string | null;
    fullNameKatakana?: string | null;
    dateOfBirth?: Date | null;
  };
};

export type RuleResult = {
  text: string;
  /** Terms the glossary did not know, surfaced to the operator. */
  unmatched?: string[];
  note?: string;
};

const str = (v: unknown): string =>
  v === null || v === undefined ? '' : String(v).trim();

/** 氏名: katakana and English together — spec §6.1. */
export function fullNameCombined(ctx: RuleContext): RuleResult {
  const katakana =
    str(ctx.person?.fullNameKatakana) || str(ctx.answers['A-1-2']);
  const english = str(ctx.person?.fullNameEnglish) || str(ctx.answers['A-1-1']);
  if (!katakana && !english) return { text: '' };
  if (!katakana) return { text: english };
  if (!english) return { text: katakana };
  // Katakana parts are separated by the full-width middle dot.
  const kata = katakana.replace(/[\s・･]+/g, '・');
  return { text: `${kata}／${english}` };
}

/** 年齢: derived from date of birth; the date itself is never printed (ch.13). */
export function ageFromDateOfBirth(ctx: RuleContext): RuleResult {
  const raw = ctx.person?.dateOfBirth ?? parseDate(str(ctx.answers['A-1-4']));
  if (!raw) return { text: '' };
  const now = ctx.now ?? new Date();
  let age = now.getFullYear() - raw.getFullYear();
  const m = now.getMonth() - raw.getMonth();
  if (m < 0 || (m === 0 && now.getDate() < raw.getDate())) age--;
  if (age < 0 || age > 120) return { text: '', note: '生年月日の値が不正である' };
  return { text: `${age}歳` };
}

function parseDate(v: string): Date | null {
  if (!v) return null;
  const iso = v.replace(/\//g, '-').trim();
  const d = new Date(iso);
  return Number.isNaN(d.getTime()) ? null : d;
}

/**
 * 出身地: city + state + region, e.g. パラディップ・オディシャ州（東インド）.
 * The region comes from the supplied table, never from the AI (§8.5 note).
 */
export function hometownWithRegion(ctx: RuleContext): RuleResult {
  const raw = str(ctx.answers['A-1-6']);
  if (!raw) return { text: '' };

  // Answers look like "Rajasthan, Jodhpur" or "Jodhpur, Rajasthan".
  const parts = raw
    .split(/[,、／/]/)
    .map((p) => p.trim())
    .filter(Boolean);

  let stateEntry: { japanese: string; region: string | null } | null = null;
  let stateIndex = -1;
  for (let i = 0; i < parts.length; i++) {
    const hit = ctx.glossary.regionForState(parts[i]);
    if (hit) {
      stateEntry = hit;
      stateIndex = i;
      break;
    }
  }

  if (!stateEntry) {
    return {
      text: raw,
      unmatched: [raw],
      note: '州名を対応表で特定できなかった。辞書に追加するか手修正が必要である',
    };
  }

  const city = parts.filter((_, i) => i !== stateIndex).join('・');
  const head = city ? `${city}・${stateEntry.japanese}` : stateEntry.japanese;
  return {
    text: stateEntry.region ? `${head}（${stateEntry.region}）` : head,
    unmatched: city ? [city] : [],
    note: city
      ? '都市名は英語表記のままである場合がある。必要に応じて手修正すること'
      : undefined,
  };
}

/** 取得資格と時期: e.g. 2025年12月にN3取得 — spec §6.10. */
export function jlptQualification(ctx: RuleContext): RuleResult {
  if (!ctx.jlpt) return { text: '' };
  return { text: buildQualificationLine(ctx.jlpt) };
}

/** 日本語力の説明: generated by rule from the score breakdown — spec ch.10. */
export function jlptDescription(ctx: RuleContext): RuleResult {
  if (!ctx.jlpt) return { text: '' };
  return { text: buildDescription(ctx.jlpt) };
}

/**
 * 有無 + 詳細 の組を1項目にまとめる共通処理。
 *
 * Sano-san's rule, given for 論文・学会発表 and then extended to every field of
 * this shape: where there is something to report, print the detail alone — the
 * 有無 answer says nothing the detail does not already say, and 「あり」 above a
 * citation reads as a form rather than as a document. Where there is nothing,
 * print 「なし」.
 *
 * The one case her wording does not cover is an answer that says something
 * exists with the detail left blank. Printing 「なし」 there would state the
 * opposite of what the person answered, so the 有無 answer is printed instead
 * (Japanese side only, §4.1) and the operator can fill in the detail.
 *
 * The detail is never summarised — for a paper, author order, peer-review
 * status, journal and year are the whole value of the entry.
 */
function presenceWithDetail(
  presenceAnswer: unknown,
  detailAnswer: unknown,
): RuleResult {
  const presence = str(presenceAnswer);
  const detail = str(detailAnswer);

  if (!presence && !detail) return { text: '' };
  if (detail) return { text: detail };

  // Nothing written in the detail box.
  if (!presence || isNoneOption(presence)) return { text: 'なし' };

  const japanese = japaneseSideOfOption(presence);
  if (/^(あり|有|yes)$/i.test(japanese)) {
    return {
      text: 'なし',
      note: '「あり」と回答されているが詳細が未入力である。詳細を確認すること',
    };
  }
  return {
    text: japanese,
    note: '詳細（自由記述）が未入力である。必要に応じて追記すること',
  };
}

/** 論文・学会発表: H-2-1（有無）+ H-2-2（詳細）. */
export function publicationsCombined(ctx: RuleContext): RuleResult {
  return presenceWithDetail(ctx.answers['H-2-1'], ctx.answers['H-2-2']);
}

/** 特許: H-2-5（有無）+ H-2-6（詳細）. Same rule, on Sano-san's instruction. */
export function patentsCombined(ctx: RuleContext): RuleResult {
  return presenceWithDetail(ctx.answers['H-2-5'], ctx.answers['H-2-6']);
}

/**
 * 修士論文・卒業論文: the supervisor and laboratory (H-2-4) as 確定事実.
 *
 * The field itself is AI-written from H-2-3, but a supervisor's name and a
 * laboratory's name are proper nouns that must survive verbatim, so they are
 * handed to the prompt as a fact it is forbidden to contradict rather than
 * being left to the model to compose.
 */
export function thesisSupervisorFact(ctx: RuleContext): RuleResult {
  const supervisor = str(ctx.answers['H-2-4']);
  if (!supervisor) return { text: '' };
  return { text: `指導教員・研究室：${supervisor}` };
}

export type RuleFn = (ctx: RuleContext) => RuleResult;

export const RULES: Record<string, { label: string; run: RuleFn }> = {
  full_name_combined: { label: '氏名（カタカナ＋英語）', run: fullNameCombined },
  age_from_dob: { label: '年齢（生年月日から算出）', run: ageFromDateOfBirth },
  hometown_with_region: { label: '出身地（州・地域区分を付記）', run: hometownWithRegion },
  jlpt_qualification: { label: 'JLPT取得資格と時期', run: jlptQualification },
  jlpt_description: { label: 'JLPT日本語力の説明', run: jlptDescription },
  publications_combined: { label: '論文・学会発表（有無と詳細をまとめる）', run: publicationsCombined },
  patents_combined: { label: '特許（有無と詳細をまとめる）', run: patentsCombined },
  thesis_supervisor_fact: {
    label: '指導教員・研究室（確定事実として生成に渡す）',
    run: thesisSupervisorFact,
  },
};

export function runRule(ruleKey: string, ctx: RuleContext): RuleResult {
  const rule = RULES[ruleKey];
  if (!rule) {
    return { text: '', note: `未登録の規則キー: ${ruleKey}` };
  }
  return rule.run(ctx);
}

export * from './jlpt';
